name: passe

options:
  bundleIdPrefix: io.github.takeiteasy
  createIntermediateGroups: true
  deploymentTarget:
    macOS: "12.0"

settings:
  GCC_C_LANGUAGE_STANDARD: c11
  CLANG_WARN_DOCUMENTATION_COMMENTS: false

targets:
  libspectre:
    type: library.dynamic
    platform: macOS
    sources:
      - path: src/spectre.c
      - path: src/spectre.h
    settings:
        OTHER_CFLAGS: [-DNO_MAIN]
  spectre:
    type: tool
    platform: macOS
    sources:
      - path: src/spectre.c
      - path: src/spectre.h
  passe:
    type: application
    platform: macOS
    info:
        path: Info.plist
    sources:
      - path: src/passe-gui.m
      - path: project.yml
        type: folder
      - path: Makefile
        type: folder
      - path: README.md
        type: folder
      - path: src/passe-cli.rb
        type: folder
      - path: src/spectre.rb
        type: folder
    dependencies:
        - sdk: Carbon.framework
